# fly.toml app configuration file generated for ghostmail-smtp-server on 2024-06-24T14:00:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ghostmail-smtp-server'
primary_region = 'lax'

[build]
dockerfile = '../../Dockerfile.smtp'

[[services]]
protocol = 'tcp'
internal_port = 8080

[[services.ports]]
port = 25

[[services.ports]]
port = 465
handler = "tls"

[[services.ports]]
port = 587

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
