services:
  client:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/ghostmail-client:latest
    platform: linux/arm64
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo1:27017,mongo2:27018,mongo3:27019/ghostmail?authSource=admin&replicaSet=rs0
      - SESSION_SECRET=${SESSION_SECRET}
      - VITE_MAIL_DOMAIN=ghostmail.dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`ghostmail.dev`)||Host(`www.ghostmail.dev`)||Host(`stage.ghostmail.dev`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls.certresolver=myresolver"
      - "traefik.http.services.client.loadbalancer.server.port=3000"
      - "traefik.http.services.client.loadbalancer.passhostheader=true"
    networks:
      - traefik-public
      - mongo-internal
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  smtp-server:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER}/ghostmail-smtp:latest
    platform: linux/arm64
    ports:
      - "25:2525"
      - "587:2525"
    environment:
      - MONGODB_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo1:27017,mongo2:27018,mongo3:27019/ghostmail?authSource=admin&replicaSet=rs0
      - SMTP_DOMAIN=ghostmail.dev
      - SMTP_PORT=${SMTP_PORT:-2525}
      - KEY_FILE_PATH=/certs/ghostmail.dev/privatekey.key
      - CERT_FILE_PATH=/certs/ghostmail.dev/certificate.crt
    volumes:
      - "/home/${OCI_USER}/infra/certs:/certs:ro"
    networks:
      - mongo-internal
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traefik-public:
    external: true
  mongo-internal:
    external: true
