# fly.toml app configuration file generated for ghostmail on 2024-06-21T16:25:51-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ghostmail'
primary_region = 'lax'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
dockerfile = "../../Dockerfile.gql-server"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
